config/routes.rb
SmallCommunity::Application.routes.draw do
  devise_for :users

    root 'posts#index'
    resources :posts
    resources :events
    resources :announces

end

app/models/announce.rb
class Announce < ActiveRecord::Base
  belongs_to :user
  validates :announce_content, length: {maximum:200,minimum:1}
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :post_content, length: {maximum:200,minimum:1}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :events
  has_many :announces

  def officer?
    role == 'officer'
  end

  def student?
    role == 'student'
  end

  def circle?
    role == 'circle'
  end
end

app/controllers/announces_controller.rb
class AnnouncesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index]

  def index
    @announce = Announce.new
    @announces = Announce.all
  end

  def create
    announce = Announce.new(announce_params)
    announce.user = current_user
    announce.save
    redirect_to announces_path
  end

  private

  def announce_params
    params[:announce].permit(:announce_content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :role
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index]

  def index
    @event_date = Date.today()
    @event = Event.new
    @events = Event.all
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.save
    redirect_to events_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params[:event].permit(:event_title,:event_date,:event_content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index]

  def index
    @post = Post.new
    @posts = Post.all
  end

  def create
    post = Post.new(post_params)
    post.user = current_user
    post.save
    redirect_to posts_path
  end

  private

  def post_params
    params[:post].permit(:post_content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:create,:index]
  
end

app/helpers/announces_helper.rb
module AnnouncesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/announces/index.html.erb
<% if current_user.officer? %>
  <div class="wrapper" id="wrapper-form">
    <h2>アナウンス作成</h2>
    <div class="post-field">
      <%= form_for @announce do |f| %>
        <%= f.text_area :announce_content %>
        <%= f.submit "投稿する" %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="wrapper" id="wrapper-list">
  <div class="post-list">
    <ul>
      <% @announces.each do |announce|%>
          <% if announce.user.name.present? %>
              <li><%= announce.user.name %></li>
          <% else %>
              <li><%= announce.user.email %></li>
          <% end %>
          <li><%= announce.announce_content %></li>
      <% end %>
    </ul>
  </div>

</div>

app/views/events/index.html.erb
<% if current_user.circle? || current_user.officer? %>
  <div class="wrapper" id="wrapper-form">
    <h2>イベント告知</h2>
    <div class="post-field">
      <%= form_for @event do |f| %>
        <h3>タイトル</h3>
          <%= f.text_field :event_title %>
          <h3>日付</h3>
          <%= f.text_field :event_date, :class => 'datepicker' %>
          <h3>内容</h3>
          <%= f.text_area :event_content %>
          <%= f.submit "投稿する" %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="wrapper" id="wrapper-list">
  <div class="post-list">
  <% @events.each do |event|%>
    <ul>
      <% if event.user.name.present? %>
        <li><%= event.user.name %></li>
      <% else %>
        <li><%= event.user.email %></li>
      <% end %>
      <p>タイトル</p>
      <li class="title-list"><%= event.event_title %></li>
      <p>日付</p>
      <li class="date-list"><%= event.event_date %></li>
      <p>内容</p>
      <li class="content-list"><%= event.event_content %></li>
      <% if event.user == current_user %>
        <p><%= link_to '削除', event_path(event.id), method: 'delete'%></p>
      <% end %>
    </ul>
    <% end %>
    </div>
</div>




<script type="text/javascript">
    $(document).ready(function(){
        $('.datepicker').datepicker({
            format: "yyyy-mm-dd"
        });
    });
</script>

app/views/layouts/_community_wrapper.html.erb
<div class="community-form">
  <div class="sidebar-left-content">
    <% if user_signed_in? %>
        <h2>コミュニティ</h2>
        <ul class="ibaraki-unv">
          <li><a href="https://i-student.ibaraki.ac.jp/">Live Campus</a></li>
          <li><a href="https://renandi.ipc.ibaraki.ac.jp/renandi/index.jsp">RENANDI</a></li>
          <li><a href="http://www.ipc.ibaraki.ac.jp/">IT基盤センター</a></li>
          <li><a href="https://adfs.vc.ibaraki.ac.jp/adfs/ls/?wa=wsignin1.0&wtrealm=urn:federation:MicrosoftOnline&wctx=wreply%3Dhttps:%252F%252Fportal.microsoftonline.com">Office365</a></li>
        </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmallCommunity</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <div class="header-left">
    <ul>
      <li><%= link_to "ポスト", posts_path %></li>
      <li><%= link_to "イベント", events_path %></li>
      <li><%= link_to "アナウンス", announces_path %></li>
    </ul>
      </div>
    <div class="header-right">
    <ul>
    <% if user_signed_in? %>
        <li>Logged in as <strong><%= current_user.email %></strong></li>
        <li><%= link_to "プロフィール変更", edit_user_registration_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    <% else %>
        <li><%= link_to "サインイン", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
    </ul>
    </div>
  </nav>
</header>
<div class="main-content">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</div>

</body>
</html>

app/views/posts/index.html.erb
<div class="wrapper" id="wrapper-form">
  <%= form_for @post do |f| %>
    <%= f.text_area :post_content %>
    <%= f.submit "Add a New Post" %>
  <% end %>
</div>

<div class="wrapper" id="wrapper-list">
  <div class="post-list">
    <ul>
      <% @posts.each do |post|%>
        <% if post.user.name.present? %>
          <li><%= post.user.name %></li>
        <% else %>
          <li><%= post.user.email %></li>
        <% end %>
        <li><%= post.post_content %></li>
      <% end %>
    </ul>
  </div>
</div>